package managers;

import models.Producer;
import models.Timetable;
import models.TimetableEntry;

/**
 * Created by kristinesundtlorentzen on 2/3/15.
 */
public class ProducerManager {

    public void generateTimetable(Producer producer, int startTick, int tickBetweenArrivals, int numberOfArrivals,
                                  int numberOfPassengers) {

        if(tickBetweenArrivals == 0) tickBetweenArrivals = 1;

        Timetable timetable = new Timetable();
        timetable.setName("Autogenerated timetable");

        int currentTick = startTick;

        for(int i = 0; i < numberOfArrivals; i++) {
            timetable.getArrivals().add(new TimetableEntry(currentTick, numberOfPassengers));
            currentTick += tickBetweenArrivals;
        }

        producer.setTimetable(timetable);
    }
}
