package helpers;

import models.Producer;
import models.Timetable;
import models.TimetableEntry;

import javax.ejb.Singleton;

/**
 * A helper with helper method(s) for {@link models.Producer}
 */
@Singleton
public class ProducerHelper {

    /**
     * Generates a {@link models.Timetable} for a producer
     *
     * @param producer the producer for which we want to generate the timetable
     * @param startTick the time the first producer arrives
     * @param tickBetweenArrivals amount of time between arrivals
     * @param numberOfArrivals amount of arrivals
     * @param numberOfPassengers the number of entites that the producer produces pr arrival
     */
    public void generateTimetable(Producer producer, int startTick, int tickBetweenArrivals, int numberOfArrivals,
                                  int numberOfPassengers) {

        if(tickBetweenArrivals == 0) tickBetweenArrivals = 1;

        Timetable timetable = new Timetable();
        timetable.setName("Autogenerated timetable");

        int currentTick = startTick;

        for(int i = 0; i < numberOfArrivals; i++) {
            timetable.getArrivals().add(new TimetableEntry(currentTick, numberOfPassengers));
            currentTick += tickBetweenArrivals;
        }

        producer.setTimetable(timetable);
        producer.setNumberOfArrivals(timetable.getArrivals().size());
        producer.setTimeBetweenArrivals(tickBetweenArrivals);
        producer.setTimeBetweenArrivals( tickBetweenArrivals );
        producer.setPersonsPerArrival( numberOfPassengers );
    }
}
